### ISSUE TITLE
After Post (Published) or Post (Draft) ,display Object not found! 404 error

### ISSUE THREAD

**Issue by crfeng** [githubjeka/angular-yii2#8]
After fixed #7 issue, when  Post (Published) or Post (Draft) new data, data was successful insert in DB,bug URL can't redirect to new post info page. display following message when route to http://sitename.com/post/10:

"Object not found!

The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

Error 404"

return to main page and click new post message manually is ok.

**Comment by githubjeka** [comment]
Problem of github page :(

Related https://github.com/AngularYii2/angularyii2.github.io/issues/3

**Comment by githubjeka** [comment]
Fixed in https://github.com/AngularYii2/angularyii2.github.io/commit/f2247e7186b0c4a14082869251fffba51981c1c1

Thank you for contribute.
